[package]
name = "silence_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ecdsa = { version = "0.12", features = ["arithmetic"] }
k256 = "0.13.3"
sha2 = "0.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
generic-array = "0.14"
