[package]
name = "task_1"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = { version = "0.10.8" }
k256 = "0.10" 
generic-array = "1.1.0"
crypto-bigint = "=0.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"