[package]
name = "task_2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4" 
web-sys = { version = "0.3", features = ["WebSocket", "console"]}
console_error_panic_hook = "0.1.7"